### ISSUE TITLE
Add Bookmark as plugin

### ISSUE THREAD

**Issue by BoopathySrinivasan** [RasmusRummel/ckeditor5-bookmark#2]
I'm trying to add a bookmark plugin in the toolbar as per your suggestion in the CKEditor 5. But Here we are using Decouple editor instead of Classic editor.

But It throws below error
ERROR Error: Uncaught (in promise): CKEditorError: CKEditor-duplicated-modules: Some CKEditor 5 modules are duplicated.

In the node modules, there is a separate folder for the ckeditor5-bookmark with version 1.0.3.

**Comment by RasmusRummel** [comment]
Hi BoopathySrinivasan, sorry I just see your comment now (2 hours after you closed the thread). If you are still interested, I will look into it ?

**Comment by nfplee** [comment]
I have the same problem. I am using version 21 but the dependenices in the packages.json file pulls in an older verison which causes this issue.

**Comment by RasmusRummel** [comment]
Hi nfplee, it is a looong time since I have worked with CKEditor, but I will take a look tomorrow if I can fix the problem. I will let you know.

**Comment by RasmusRummel** [comment]
nfplee, ok it took me quite a time to read up on CKEditor 5 plugin creation, however I have updated the ckeditor5-bookmark plugin to version 1.1.1 - it works with CKEditor 5 version 22.0.0 (I know you have version 21, if you have problems send me the error messages).

**Comment by nfplee** [comment]
@RasmusRummel i've created a few plugins myself so I feel your pain. Still it's much easier than v4. Thanks for updating it, i'll upgrade to version 22 and let you know if I have any problems.

**Comment by nfplee** [comment]
Just upgraded and it worked fine. I then thought I'd try upgrading to v23 as that's just been released but I got the same problem. I wonder if it's worth changing the dependencies to devDependencies?

**Comment by RasmusRummel** [comment]
I made a new version, 1.1.2, which specifies it's dependencies using "x" instead of "22.0.0" (you can take a look at the package.json file to check it out).

Try the new version and tell me if it works with CKEditor 5 version 23.

**Comment by nfplee** [comment]
Perfect thanks that did the trick. You can now close this issue.
